"""empty message

Revision ID: 03be8929b462
Revises: 5f0fca22b40e
Create Date: 2017-09-23 10:28:28.290576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03be8929b462'
down_revision = '5f0fca22b40e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_session', sa.Column('annotations', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_session', 'annotations')
    # ### end Alembic commands ###
