"""empty message

Revision ID: 0f950b853581
Revises: b77f52947e07
Create Date: 2017-08-24 19:20:38.296669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f950b853581'
down_revision = 'b77f52947e07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('instructions', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises', 'instructions')
    # ### end Alembic commands ###
