"""empty message

Revision ID: 171d32378100
Revises: 0175705d0574
Create Date: 2017-09-12 10:46:04.499464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '171d32378100'
down_revision = '0175705d0574'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_session_exercises', sa.Column('resistance', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_session_exercises', 'resistance')
    # ### end Alembic commands ###
