"""empty message

Revision ID: 20dfeab949d1
Revises: 40946baf1601
Create Date: 2017-09-25 09:45:28.911768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20dfeab949d1'
down_revision = '40946baf1601'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('height', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('weight', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'weight')
    op.drop_column('users', 'height')
    # ### end Alembic commands ###
