"""empty message

Revision ID: 2734c5a64fef
Revises: 0f950b853581
Create Date: 2017-09-12 10:00:02.866271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2734c5a64fef'
down_revision = '0f950b853581'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_session_exercises', sa.Column('ordinal_number', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_session_exercises', 'ordinal_number')
    # ### end Alembic commands ###
