"""empty message

Revision ID: 35db36e66114
Revises: 7cbd027827e4
Create Date: 2017-08-06 16:36:22.946611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35db36e66114'
down_revision = '7cbd027827e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercises_muscles',
    sa.Column('exercise_id', sa.Integer(), nullable=True),
    sa.Column('muscle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['muscle_id'], ['muscles.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercises_muscles')
    op.drop_table('exercises')
    # ### end Alembic commands ###
