"""empty message

Revision ID: 3e67097bcb82
Revises: 4019169413bb
Create Date: 2017-09-26 12:48:04.666256

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3e67097bcb82'
down_revision = '4019169413bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises', 'percentage_of_bodyweight')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('percentage_of_bodyweight', mysql.FLOAT(), nullable=True))
    # ### end Alembic commands ###
