"""empty message

Revision ID: 4019169413bb
Revises: cbd66b1a1265
Create Date: 2017-09-26 12:47:18.191113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4019169413bb'
down_revision = 'cbd66b1a1265'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('percentage_of_bodyweight', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises', 'percentage_of_bodyweight')
    # ### end Alembic commands ###
