"""empty message

Revision ID: 40946baf1601
Revises: d4a775995155
Create Date: 2017-09-24 16:52:40.430253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40946baf1601'
down_revision = 'd4a775995155'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('percentage_of_bodyweight', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises', 'percentage_of_bodyweight')
    # ### end Alembic commands ###
