"""empty message

Revision ID: 4a104193369c
Revises: 8193776495b1
Create Date: 2018-12-17 11:47:48.087169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a104193369c'
down_revision = '8193776495b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('short_name', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'short_name')
    # ### end Alembic commands ###
