"""empty message

Revision ID: 5423ced65ade
Revises: 4a104193369c
Create Date: 2018-12-17 13:41:49.230984

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5423ced65ade'
down_revision = '4a104193369c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_tests', sa.Column('timestamp', sa.Integer(), nullable=True))
    op.drop_column('users_tests', 'done_timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_tests', sa.Column('done_timestamp', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('users_tests', 'timestamp')
    # ### end Alembic commands ###
