"""empty message

Revision ID: 5f0fca22b40e
Revises: b35034f4d29c
Create Date: 2017-09-22 12:28:31.923956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f0fca22b40e'
down_revision = 'b35034f4d29c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('mechanics', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises', 'mechanics')
    # ### end Alembic commands ###
