"""empty message

Revision ID: 628ca0d1265d
Revises: 07e7b4c65bf8
Create Date: 2017-09-22 12:22:33.572638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '628ca0d1265d'
down_revision = '07e7b4c65bf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('utility', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises', 'utility')
    # ### end Alembic commands ###
