"""empty message

Revision ID: 7cbd027827e4
Revises: 2021226aa61d
Create Date: 2017-08-06 13:20:08.505533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cbd027827e4'
down_revision = '2021226aa61d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('main_muscle_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sub_muscle_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('main_muscle_group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['main_muscle_group_id'], ['main_muscle_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('muscles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('sub_muscle_group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sub_muscle_group_id'], ['sub_muscle_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('muscles')
    op.drop_table('sub_muscle_groups')
    op.drop_table('main_muscle_groups')
    # ### end Alembic commands ###
