"""empty message

Revision ID: 8193776495b1
Revises: a68bdb0f4634
Create Date: 2018-12-17 10:59:24.802783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8193776495b1'
down_revision = 'a68bdb0f4634'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('unit', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'unit')
    # ### end Alembic commands ###
