"""empty message

Revision ID: 8b005041fe64
Revises: 35db36e66114
Create Date: 2017-08-07 10:59:45.669061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b005041fe64'
down_revision = '35db36e66114'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises_muscles', sa.Column('priority', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises_muscles', 'priority')
    # ### end Alembic commands ###
