"""empty message

Revision ID: 8e07dd4c884c
Revises: bff8521418bd
Create Date: 2017-09-23 11:56:45.933780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e07dd4c884c'
down_revision = 'bff8521418bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_session_exercises', sa.Column('reps', sa.String(length=50), nullable=True))
    op.add_column('training_session_exercises', sa.Column('sets', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_session_exercises', 'sets')
    op.drop_column('training_session_exercises', 'reps')
    # ### end Alembic commands ###
