"""empty message

Revision ID: 911f1004b2b0
Revises: 8b005041fe64
Create Date: 2017-08-08 14:37:22.902905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '911f1004b2b0'
down_revision = '8b005041fe64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('compound_isolated', sa.SmallInteger(), nullable=True))
    op.add_column('exercises', sa.Column('force', sa.String(length=5), nullable=True))
    op.add_column('exercises', sa.Column('type', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises', 'type')
    op.drop_column('exercises', 'force')
    op.drop_column('exercises', 'compound_isolated')
    # ### end Alembic commands ###
