"""empty message

Revision ID: a68bdb0f4634
Revises: 9247e5832834
Create Date: 2018-12-08 23:00:06.547340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a68bdb0f4634'
down_revision = '9247e5832834'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_session_exercises', sa.Column('mark', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_session_exercises', 'mark')
    # ### end Alembic commands ###
