"""empty message

Revision ID: b35034f4d29c
Revises: 628ca0d1265d
Create Date: 2017-09-22 12:28:02.629271

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b35034f4d29c'
down_revision = '628ca0d1265d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises', 'compound_isolated')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('compound_isolated', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
