"""empty message

Revision ID: b385a5574598
Revises: 09c9c2ce0aab
Create Date: 2018-10-24 17:57:42.679447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b385a5574598'
down_revision = '09c9c2ce0aab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_session', sa.Column('done', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_session', 'done')
    # ### end Alembic commands ###
