"""empty message

Revision ID: b77f52947e07
Revises: 
Create Date: 2017-08-20 19:38:58.120127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b77f52947e07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('exercises', sa.Column('equipment', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'exercises', 'equipment', ['equipment'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exercises', type_='foreignkey')
    op.drop_column('exercises', 'equipment')
    op.drop_table('equipment')
    # ### end Alembic commands ###
