"""empty message

Revision ID: bff8521418bd
Revises: 03be8929b462
Create Date: 2017-09-23 11:56:09.916501

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bff8521418bd'
down_revision = '03be8929b462'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_session_exercises', 'sets')
    op.drop_column('training_session_exercises', 'reps')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_session_exercises', sa.Column('reps', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('training_session_exercises', sa.Column('sets', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
