"""empty message

Revision ID: cbd66b1a1265
Revises: 20dfeab949d1
Create Date: 2017-09-26 12:46:59.774500

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cbd66b1a1265'
down_revision = '20dfeab949d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises', 'percentage_of_bodyweight')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('percentage_of_bodyweight', mysql.FLOAT(), nullable=True))
    # ### end Alembic commands ###
