"""empty message

Revision ID: d279b9e6985c
Revises: a1578d56ef16
Create Date: 2018-10-23 14:39:28.416181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd279b9e6985c'
down_revision = 'a1578d56ef16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('img_link', sa.String(length=64), nullable=True))
    op.add_column('exercises', sa.Column('video_description', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises', 'video_description')
    op.drop_column('exercises', 'img_link')
    # ### end Alembic commands ###
