"""empty message

Revision ID: e14bc9307c90
Revises: ffe3d85d9b3b
Create Date: 2017-09-12 10:56:51.204110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e14bc9307c90'
down_revision = 'ffe3d85d9b3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_session_exercises', sa.Column('exercise', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_session_exercises', 'exercise')
    # ### end Alembic commands ###
