"""empty message

Revision ID: e798041ebc6f
Revises: 5423ced65ade
Create Date: 2018-12-17 13:43:23.600276

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e798041ebc6f'
down_revision = '5423ced65ade'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('users_tests', sa.Column('date_done', sa.DateTime(), nullable=True))
    # op.drop_column('users_tests', 'timestamp')
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_tests', sa.Column('timestamp', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('users_tests', 'date_done')
    # ### end Alembic commands ###
