"""empty message

Revision ID: f2b47e8f1253
Revises: c7817ddb3c5b
Create Date: 2018-12-19 12:48:02.327445

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f2b47e8f1253'
down_revision = 'c7817ddb3c5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('anthropometry_users_tests', 'vinjak_mass')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anthropometry_users_tests', sa.Column('vinjak_mass', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
